import type { TokenRow } from '@/lib/actions/tokens';

const TYPE_PREFIX: Record<string, string> = {
  color:      'color',
  typography: 'font',
  spacing:    'spacing',
  radius:     'radius',
};

const TYPE_LABEL: Record<string, string> = {
  color:      'Color',
  typography: 'Typography',
  spacing:    'Spacing',
  radius:     'Radius',
};

const TYPE_ORDER = ['color', 'typography', 'spacing', 'radius'];

function toVarName(tokenName: string, prefix: string): string {
  let slug = tokenName
    .replace(/[()]/g, '')
    .replace(/\//g, '-')
    .replace(/\s+/g, '-')
    .toLowerCase();
  // Remove redundant leading prefix segments (e.g. spacing/spacing-4 → --spacing-4)
  while (slug.startsWith(`${prefix}-`)) {
    slug = slug.slice(prefix.length + 1);
  }
  return `--${prefix}-${slug}`;
}

function extractDisplayValue(token: TokenRow, type: string): string {
  if (type === 'color') {
    try {
      const parsed = JSON.parse(token.value) as { hex?: string };
      return parsed.hex ?? token.raw ?? token.value;
    } catch {
      return token.raw ?? token.value;
    }
  }
  return token.raw ?? token.value;
}

interface VarLine { varName: string; value: string }
interface TokenGroup { groupName: string; items: VarLine[] }

function buildGroups(tokens: TokenRow[], prefix: string): TokenGroup[] {
  const map = new Map<string, VarLine[]>();
  for (const token of tokens) {
    const slashIdx = token.name.indexOf('/');
    const group = slashIdx >= 0 ? token.name.slice(0, slashIdx) : '';
    const varName = toVarName(token.name, prefix);

    // Typography: parse JSON value → emit font shorthand + separate -ls variable
    if (prefix === 'font') {
      try {
        const parsed = JSON.parse(token.value) as {
          fontFamily?: string; fontWeight?: number; fontSize?: number;
          lineHeight?: string; letterSpacing?: string;
        };
        if (parsed.fontFamily) {
          const fontShorthand = `${parsed.fontWeight} ${parsed.fontSize}px/${parsed.lineHeight} '${parsed.fontFamily}'`;
          if (!map.has(group)) map.set(group, []);
          map.get(group)!.push({ varName, value: fontShorthand });
          if (parsed.letterSpacing && parsed.letterSpacing !== '0') {
            map.get(group)!.push({ varName: `${varName}-ls`, value: parsed.letterSpacing });
          }
          continue;
        }
      } catch { /* not JSON typography — fall through */ }
    }

    // String: wrap in quotes so value is valid for CSS content property
    const value = token.type === 'string'
      ? `"${(token.raw ?? token.value).replace(/"/g, '\\"')}"`
      : extractDisplayValue(token, prefix === 'color' ? 'color' : 'other');

    if (!map.has(group)) map.set(group, []);
    map.get(group)!.push({ varName, value });
  }
  return Array.from(map.entries()).map(([groupName, items]) => ({ groupName, items }));
}

/** TokenRow 배열 → :root { ... } CSS 문자열 */
export function generateCssCode(tokens: TokenRow[], type: string): string {
  const prefix = TYPE_PREFIX[type] ?? type;
  const groups = buildGroups(tokens, prefix);

  const allItems = groups.flatMap((g) => g.items);
  if (allItems.length === 0) return '/* 토큰이 없습니다. */';

  const lines: string[] = [
    `/* Generated by PixelForge · ${formatDate()} */`,
    '',
    ':root {',
  ];

  for (let gi = 0; gi < groups.length; gi++) {
    const { groupName, items } = groups[gi];
    if (gi > 0) lines.push('');
    if (groupName) lines.push(`  /* ${groupName} */`);
    for (const { varName, value } of items) {
      lines.push(`  ${varName}: ${value};`);
    }
  }

  lines.push('}');
  return lines.join('\n');
}

function formatDate(): string {
  return new Date()
    .toLocaleDateString('ko-KR', { year: 'numeric', month: '2-digit', day: '2-digit' })
    .replace(/\. /g, '-')
    .replace('.', '');
}

/** 모든 타입의 TokenRow → 단일 :root { } CSS 문자열 (타입별 섹션) */
export function generateAllCssCode(allTokens: TokenRow[]): string {
  if (allTokens.length === 0) return '/* 토큰이 없습니다. */';

  const byType = new Map<string, TokenRow[]>();
  for (const token of allTokens) {
    if (!byType.has(token.type)) byType.set(token.type, []);
    byType.get(token.type)!.push(token);
  }

  const orderedTypes = [
    ...TYPE_ORDER.filter((t) => byType.has(t)),
    ...[...byType.keys()].filter((t) => !TYPE_ORDER.includes(t)),
  ];

  const lines: string[] = [
    `/* Generated by PixelForge · ${formatDate()} */`,
    '',
    ':root {',
  ];

  let firstType = true;
  for (const type of orderedTypes) {
    const typeTokens = byType.get(type)!;
    const prefix = TYPE_PREFIX[type] ?? type;
    const label = TYPE_LABEL[type] ?? type;
    const groups = buildGroups(typeTokens, prefix);
    const allItems = groups.flatMap((g) => g.items);
    if (allItems.length === 0) continue;

    if (!firstType) lines.push('');
    lines.push(`  /* ── ${label} ── */`);
    firstType = false;

    for (let gi = 0; gi < groups.length; gi++) {
      const { groupName, items } = groups[gi];
      if (gi > 0) lines.push('');
      if (groupName) lines.push(`  /* ${groupName} */`);
      for (const { varName, value } of items) {
        lines.push(`  ${varName}: ${value};`);
      }
    }
  }

  lines.push('}');
  return lines.join('\n');
}

/**
 * CSS 코드를 unified diff (컨텍스트 라인만) 형식으로 래핑.
 * diff2html이 변경 없는 파일 뷰로 렌더링하도록 한다.
 */
export function wrapAsDiff(cssCode: string, filename = 'tokens.css'): string {
  const codeLines = cssCode.split('\n');
  const n = codeLines.length;
  const contextLines = codeLines.map((line) => ` ${line}`).join('\n');
  return [
    `diff --git a/${filename} b/${filename}`,
    `--- a/${filename}`,
    `+++ b/${filename}`,
    `@@ -1,${n} +1,${n} @@`,
    contextLines,
  ].join('\n');
}
